-- recruit_007_admins
-- The people who can sign in, and what each of them may do.
--
-- Until now the answer to "who has a login" lived in ADMIN_USERS, an
-- environment variable. That made adding a colleague a deploy: server access,
-- a hash generated by hand, a restart, and no way to remove anybody quickly.
-- With one manager that was tolerable. With Brad, Priyanshu and more later it
-- is not — so the list becomes data.
--
-- Spec §8.1 asks for a `recruitment.manage` permission and an actor recorded
-- on every action. The actor half has always been there; this adds the
-- permission half, which matters before a second person has a login rather
-- than after.

BEGIN;

/*
 * Two roles, and deliberately only two.
 *
 *   reviewer       reads applications, decides them, downloads CVs, works the
 *                  calendar and records attendance. Everything to do with
 *                  candidates.
 *
 *   administrator  all of that, plus the controls that change how the portal
 *                  behaves — the availability rules, the feature flags, how
 *                  long CVs are kept, and who else has a login.
 *
 * The line is drawn where the damage is: someone hired to screen CVs should
 * not also be able to switch the public portal off or shorten the retention
 * period. More roles could be invented, but each one is a question somebody
 * has to answer for every new colleague, and two answers the real question.
 */
CREATE TYPE admin_role AS ENUM ('reviewer', 'administrator');

CREATE TABLE recruit_admins (
  id             serial PRIMARY KEY,

  -- What they type to sign in, and what appears on their decisions. Both
  -- unique and case-insensitive: "Brad" and "brad" must not be two people.
  username       citext NOT NULL UNIQUE CHECK (length(username) BETWEEN 2 AND 40),
  email          citext NOT NULL UNIQUE CHECK (length(email) BETWEEN 3 AND 254),
  full_name      text CHECK (full_name IS NULL OR length(full_name) <= 120),

  -- scrypt, in the same `scrypt$salt$key` format ADMIN_USERS used, so an
  -- existing hash can be moved across without anyone changing their password.
  password_hash  text NOT NULL,

  role           admin_role NOT NULL DEFAULT 'reviewer',

  -- Deactivated rather than deleted. Their name still has to make sense
  -- against the decisions they made, and recruit_audit keeps those forever.
  active         boolean NOT NULL DEFAULT true,

  created_by_email citext,
  created_at     timestamptz NOT NULL DEFAULT now(),
  updated_at     timestamptz NOT NULL DEFAULT now(),
  last_seen_at   timestamptz
);

-- Every admin request looks the signed-in person up to check they are still
-- active, so this index is on the hot path rather than a nicety.
CREATE INDEX idx_recruit_admins_active ON recruit_admins (username) WHERE active;

GRANT SELECT, INSERT, UPDATE ON recruit_admins TO :"app_role";
GRANT USAGE, SELECT ON SEQUENCE recruit_admins_id_seq TO :"app_role";

/*
 * No rows are seeded, and that is the whole bootstrap.
 *
 * A password cannot be hashed in SQL — scrypt lives in the application — so
 * this table starts empty and ADMIN_USERS keeps working while it is. The
 * moment a real row exists the environment list stops being consulted.
 *
 * That gives a way in that closes itself: applying this migration locks
 * nobody out, and adding the first real administrator retires the fallback
 * without anyone having to remember to. The team screen says which of the two
 * is currently in force, so nobody has to guess.
 */

COMMIT;
